### PR TITLE
added motion detector script

### PR DESCRIPTION
**Pull request by pBouillon**
Motion detector script

calibration and polling

### CODE REVIEW

**Comment by srbcheema1** [comment]
thanks for the PR @pBouillon 
this topic seems to be new to me .
i havent worked with sensors .
i would suggest you to add few links to tutorials or documentation for understandability of beginners 
thanks in advance

**Comment by srbcheema1** [comment]
@pBouillon 
if you found this repository interesting and helpful do give it a STAR

**Comment by pBouillon** [comment]
@srbcheema1 I used this in one of my project, I'll add a README.md in the sub-folder to explain how to use this script,
Thanks for merging !

**Comment by srbcheema1** [comment]
yupp sure @pBouillon 
you may also add a link to your repository :)
i will be glad if you give a STAR to this repository :smile:

**Comment by pBouillon** [comment]
@srbcheema1 There you go ! #25

**Pull request merged**
