### PR TITLE
Added WebScraper project #1

### PR DESCRIPTION
**Pull request by vishnuramana**
Added a WebScraper that I built using BeautifulSoup. I mainly use it for booking movie tickets once it opens for booking and also in product pages where countdowns are used 😄

### CODE REVIEW

**Comment by srbcheema1** [comment]
thanks for the PR @V1cHu 
your scrapper is amaizing .
this is perhaps the best contribution of the day
i would love to see more contributions from your side

**Comment by srbcheema1** [comment]
@V1cHu 
also donot forget to give a STAR to this repo

**Comment by vishnuramana** [comment]
@srbcheema1 Hey thanks for the merge ! Starred the repo 😄

**Comment by srbcheema1** [comment]
great @V1cHu  
i will be waiting for more scripts and contributions from your side

**Pull request merged**
