### PR TITLE
added a webcrawler

### PR DESCRIPTION
**Pull request by fabianaboldrin**
added a webcrawler that i made, hope u like it

### CODE REVIEW

**Comment by srbcheema1** [comment]
thanks for the PR @fabianaboldrin 
your crawler seems to be interesting
i would love to see more contribution from yours side

**Comment by srbcheema1** [comment]
@fabianaboldrin  i would be glad to if you would give a STAR to my repo

**Comment by fabianaboldrin** [comment]
@srbcheema1 I gave your repo a star, don't worry, happy to contribute

**Comment by srbcheema1** [comment]
thanks @fabianaboldrin 
it means alot to me

**Pull request merged**
